[package]
name = "azalea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.5"
thiserror = "1.0.48"
tl = "0.7.7"
